name: textlint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.tool-versions'
      - name: Set node version
        id: node-version
        run: echo "::set-output name=node::$(node -v)"
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ steps.node-version.outputs.node }}-${{ hashFiles('package-lock.json') }}

      - run: npm ci
      - run: npm run textlint
